FROM node:20-alpine as builder

WORKDIR /backend

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine as production

WORKDIR /backend

COPY --from=builder /backend/package*.json ./

RUN npm install --production

COPY --from=builder /backend/dist ./dist
COPY --from=builder /backend/public ./public

CMD ["node", "dist/main.js"]

EXPOSE 3000
