name: Docker Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  push:
    branches: 
      ['main', 'review-3']
  pull_request:
    branches: 
      - 'main'
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Extract metadata for backend
          id: backend-meta
          uses: docker/metadata-action@v4
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend

        - name: Build and push Docker backend image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
            context: ./backend
            file: ./backend/Dockerfile.backend
            push: true
            tags: ${{ steps.backend-meta.outputs.tags }}
            labels: ${{ steps.backend-meta.outputs.labels }}

        - name: Extract metadata for frontend
          id: frontend-meta
          uses: docker/metadata-action@v4
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend

        - name: Build and push Docker frontend image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
              context: ./frontend
              file: ./frontend/Dockerfile.frontend
              push: true
              tags: ${{ steps.backend-meta.outputs.tags }}
              labels: ${{ steps.backend-meta.outputs.labels }}